### ISSUE TITLE
Images flash large on page reload

### ISSUE THREAD

**Issue by eleanorreem** [chaynHQ/bloom-frontend#987]
### Overview
The images flash large on page reload. They shouldn't do this. See video below 

### Action Items
- [ ] Spin up bloom frontend
- [ ] Refresh the page and see the images flash large when loading. 
- [ ] Fix bug
- [ ] Run Cypress tests to ensure everything is still workng
- [ ] Commit changes and create a PR and tag @eleanorreem or @kyleecodes 

https://github.com/chaynHQ/bloom-frontend/assets/16049515/1ecde8d2-3b47-421b-8d75-3e4f14e9e10e

**Comment by ckirby19** [comment]
Hello! I would like to investigate this if no one else is working on this yet? Thanks!

**Comment by eleanorreem** [comment]
@ckirby19 Assigned! This would be a great if you could fix it! Its been bugging me 🤦

**Comment by eleanorreem** [comment]
@ckirby19 I have a feeling its something to do with these PRs - https://github.com/chaynHQ/bloom-frontend/pull/911 https://github.com/chaynHQ/bloom-frontend/pull/923 and the Next/Legacy/Image to Next/Image upgrade.

**Comment by eleanorreem** [comment]
@ckirby19 in a recent upgrade from nextjs 13-14 this has been fixed. Hope you haven't spent too much time on it. @annarhughes FYI

**Comment by ckirby19** [comment]
I hadn't taken a proper look at this anyway yet, so no worries! Out of interest, what was the change from the upgrade that fixed this problem?

**Comment by eleanorreem** [comment]
I don't know whether the recent nextjs upgrade actually just slightly hid the issue. I just noticed it happen on /account/about-you page but not on other pages. I am going to reopen but I think its much lower priority now as I can't see it happening on other pages.

**Comment by ckirby19** [comment]
I believe it just hid the issue - I can still see it on the production site and when running locally as below:
![LoadingError](https://github.com/user-attachments/assets/b4acf045-e97b-42c3-b5a0-1d926d205987)

I have just raised a simple PR that I think fixes this - but I would appreciate some eyes on it to see that it does not break anything else and that it actually works for you locally too.

**Comment by eleanorreem** [comment]
Thanks @ckirby19 closing as completed
